[package]
name = "imginfo"
version = "0.1.0"
authors = ["Panda Foss <maxi.fg13@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kamadak-exif = "0.5.4"
prettytable-rs = "0.8.0"
